version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[GH Actions]"
    labels:
      - "area/dependencies"
      - "lang/github-actions"

  # Python
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[Python]"
    labels:
      - "area/dependencies"
      - "lang/python"

  # JavaScript / TypeScript (NPM)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[npm]"
      prefix-development: "[npm dev]"
    labels:
      - "area/dependencies"
      - "lang/javascript"
      - "lang/typescript"
