default_language_version:
  python: python3.9

exclude: "^.*/migrations/.*$"
fail_fast: true

minimum_pre_commit_version: "2.16.0"

repos:
  # black (code formatting)
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  # isort (automatically sort import statements)
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  # flake8 (linting)
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          [flake8-bugbear, flake8-docstrings, flake8-django, flake8-assertive]
  # easy regex checks
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      # prohibit blank "noqa"
      - id: python-check-blanket-noqa
      # eval() is evil
      - id: python-no-eval
  # bandit (security issues)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.2
    hooks:
      - id: bandit
  # lint templates
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: 0.7.4
    hooks:
      - id: djlint-django
  # lint CSS/JS related code
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.5.3
    hooks:
      - id: stylelint
        args: [--fix]
        files: \.(scss)$
        additional_dependencies:
          # stylelint itself needs to be here when using additional_dependencies.
          - stylelint@14.5.3
          - postcss-scss
          - stylelint-config-standard
          - stylelint-config-sass-guidelines
          # - stylelint-config-property-sort-order-smacss
          - stylelint-config-prettier
  - repo: https://github.com/pycqa/doc8
    rev: 0.10.1
    hooks:
      - id: doc8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # check JSON files
      - id: check-json
      # check TOML files
      - id: check-toml
      # check YAML files
      - id: check-yaml
      # let all files end with a single new line (this *should be ensured by
      # .editorconfig already)
      - id: end-of-file-fixer
      # remove all trailing whitespaces (this *should* be ensured by
      # .editorconfig already)
      - id: trailing-whitespace
      # provide uniform line endings for the project ('lf'; this *should be
      # ensured by .editorconfig already)
      - id: mixed-line-ending
        args: [--fix, lf]
      # remove utf-8 byte order marker
      - id: fix-byte-order-marker
