# Generated by Django 4.0.2 on 2022-02-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.FloatField(help_text='The actual numerical value, without its unit', verbose_name='Reading')),
                ('timestamp', models.DateTimeField(help_text='Date and Time of the record', verbose_name='Date/Time of the record')),
                ('resource', models.ForeignKey(help_text='The resource to provide this record for', on_delete=django.db.models.deletion.CASCADE, to='consumption.resource', verbose_name='Resource Instance')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
    ]
