# Generated by Django 4.0.2 on 2022-02-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
    ]
